# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
#  docker-compose -f postresql-docker-compose.yml up
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    networks:
      - backend
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - "dbdata:/var/lib/postgresql/data"
networks:
  backend: {}
volumes:
  dbdata:
